// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations precisam de uma conexão direta (não via pgbouncer/pooler).
    // Na Vercel, defina DIRECT_URL com a connection string "Direct connection"
    // do Supabase; localmente, DATABASE_URL sozinha já funciona.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
